// Generated by CoffeeScript 1.6.3
var Socket;

if (typeof require.exists === 'function') {
  Socket = require('engine.io').Socket;
} else {
  Socket = require('engine.io-client').Socket;
}

module.exports.create = function(config) {
  var local;
  return local = {
    title: config.title != null ? config.title : 'Untitled',
    uuid: config.uuid != null ? config.uuid : void 0,
    context: config.context != null ? config.context : {},
    secret: config.secret != null ? config.secret : '',
    status: {
      value: 'pending',
      at: new Date
    },
    connect: function() {
      if (local.socket != null) {
        return local.reconnect();
      }
    }
  };
};
