// Generated by CoffeeScript 1.6.3
var EngineIoClient, debug;

debug = require('debug')('vertex-client:base');

if (typeof require.exists === 'function') {
  EngineIoClient = require('engine.io');
} else {
  EngineIoClient = require('engine.io-client');
}

module.exports.create = function(config) {
  var local, _base;
  if (config == null) {
    config = {};
  }
  if (config.connect != null) {
    (_base = config.connect).interval || (_base.interval = 1000);
  }
  return local = {
    title: config.title != null ? config.title : 'Untitled',
    uuid: config.uuid != null ? config.uuid : void 0,
    context: config.context != null ? config.context : {},
    secret: config.secret != null ? config.secret : '',
    status: {
      value: 'pending',
      at: new Date
    },
    connect: function() {
      var socket;
      if (local.socket != null) {
        return local.reconnect();
      }
      debug('connecting to %s', config.connect.uri);
      local.socket = socket = new EngineIoClient.Socket(config.connect.uri);
      socket.on('error', function(err) {
        debug('error %s', config.connect.uri, err);
        if (local.status.value === 'pending') {
          return local.reconnect('connecting');
        }
      });
      socket.on('open', function() {
        debug('opened %s', config.connect.uri);
        local.status.value = 'connected';
        local.status.at = new Date;
        if (local.connecting != null) {
          clearInterval(local.connecting);
          delete local.connecting;
        }
        if (local.reconnecting != null) {
          clearInterval(local.reconnecting);
          delete local.reconnecting;
        }
        return socket.send(JSON.stringify({
          event: 'handshake',
          data: {
            title: local.title,
            uuid: local.uuid,
            context: local.context,
            secret: local.secret
          }
        }));
      });
      socket.on('close', function() {
        debug('closed %s', config.connect.uri);
        if (local.status.value === 'denied') {
          return;
        }
        return local.reconnect('reconnecting');
      });
      return socket.on('message', function(payload) {
        var message;
        message = JSON.parse(payload);
        if (message.event === 'deny' || message.event === 'accept') {
          return local[message.event](message);
        }
      });
    },
    deny: function() {
      local.status.value = 'denied';
      local.status.at = new Date;
      return debug('denied');
    },
    accept: function() {
      local.status.value = 'accepted';
      local.status.at = new Date;
      return debug('accepted');
    },
    connecting: void 0,
    reconnecting: void 0,
    reconnect: function(type) {
      var interval;
      if (!(type === 'connecting' || type === 'reconnecting')) {
        return;
      }
      if (local[type] != null) {
        return;
      }
      interval = config.connect.interval;
      if (interval < 1000) {
        interval = 1000;
      }
      return local[type] = setInterval((function() {
        debug('%s to %s', type, config.connect.uri);
        return local.socket.open();
      }), interval);
    }
  };
};
